<?php
include_once 'config.class.php';
include_once Config::$lpfw.'sessionManager.php';
include_once Config::$lpfw.'userManager.php';
include_once Config::$lpfw.'appl.class.php';
use maierlabs\lpfw\Appl as Appl;

Appl::setSiteTitle("Iskolánk története 1993-ig");
Appl::setSiteSubTitle("Az iskolánk története a XVI század és 1993 között");
include("homemenu.inc.php");
?>
<div class="container-fluid">
<h2 class="sub_title">Az iskolánk története</h2>
<div style="text-align: center;">
	<img class="img-responsive" style="margin: auto;" src="images/ISKOLA.JPG" width="400" height="388" alt="Az iskola épülete"/><br/>
	A felvétel 1963 ban készült.
</div>

<hr>
  
<h3><a href="#001">Elöszó</a></h3>
<p>A XVI. század második felében a reformáció, majd az ellenreformáció hatására az erdélyi iskoláztatás túljutott a korábbi szűk, városi vagy szerzetesi kereteken, és bár bizonyos csoportok, felekezetek szolgálatába állt, ezt úgy tette, hogy az egyházi és a világi értelmiség nevelésével az egész lakosság felemelkedését tartotta szem előtt. Minden itteni iskola külön színt, helyi sajátosságot képviselt ugyan, de mert benne az európai műveltség egyik vagy másik iránya érvényesült, annak felerősítésével és továbbterjesztésével kapcsolódott, illetve bekapcsolta szűkebb hazánkat az egyetemes művelődés nagy áramlataiba. 
<p>A mostani Brassai Sámuel Elméleti Líceum, az erdélyi unitáriusok egykori iskolája, nemcsak hazai, hanem európai viszonylatban is egyedülálló intézmény. A XVI század belső és külső, a reformációval kezdődő politikai, vallási és ideológiai harcainak légkörében született meg, s hogy évszázadokon át nem pusztult el, mint sok más akkor keletkezett intézmény, azt fenntartói áldozatkészségének, ragaszkodásának és az erdélyi szellemiségnek köszönhette.

<h3>Az iskola megalapítása</h3>
<p>Az iskolát a XVI. század közepén, a reformáció itteni terjeszkedésének korában, a független erdélyi fejedelemség kialakulásának idején alapították. A mohácsi vész után Erdély a két nagyhatalom: a Habsburg és a török birodalom terjeszkedési célja és ütköző területe lett. Az évtizedekig tartó és sok nyomorúságot hozó versengés a török birodalom javára dőlt el, és 1556-ban Szapolyai János özvegye, Izabella, aki korábban az ország elhagyására kényszerült fiával, a törvényes trónörökössel, János Zsigmonddal együtt visszatért Erdélybe, és a Kolozsváron még abban az időben megtartott országgyűlés úgy határozott, hogy mivel János Zsigmond még kiskorú: "nem tartható képesnek és alkalmasnak a kormányzásra, ezért öt éven át az ország vezetésének legfőbb hatalmát a királyné gyakorolja." Ugyanannak az országgyűlésnek egy másik határozata kimondta, hogy a "papi javak, valamint a székesegyházi adók egész Erdélyben szálljanak át a királyi kincstárra." E javak lefoglalásával együtt a szerzetesrendeket is feloszlatták, és a fekete barátokat az országból kitiltották, sőt a fehérvári katolikus püspök Bornemissza Pál is kénytelen volt elhagyni az országot. 
<p>Ezek az események hátrányosan befolyásolták az iskoláztatás helyzetét és annak teljes átszervezését tették szükségessé. Az 1557. február 6-15 között tartott gyulafehérvári országgyűlésen a karok és a rendek  szomorúan állapítják meg, hogy "az ifjúság nevelése elhanyagoltatott, és a műveletlenség napról napra terebélyesedik és növekszik", ezért arra kérik a királynőt, hogy ezekben az ifjúságot "tudós és nyelvekben jártas férfiak kegyesen és biztonságosan neveljék". Kérésüket a királynő méltányosnak tartotta, és a szerzetesek két kolostorát, a vásárhelyit és a kolozsvárit erre a célre kijelölte, amit "az ország urai tetszésnyilvánítással fogadtak" s köszönetüket és teljes hűségüket fejezték ki a királynőnek. 
<p>Öt hónap múlva a június 1-10 között tartott tordai országgyűlésen a királynő véglegesen jóváhagyja, hogy "Kolozsváron a domonkosok zárdájában, Vásárhelyen a ferencesek zárdájában és  Váradon a mindszentek zárdájában iskolák állíttassanak fel", mégis úgy, hogy Váradon megmaradjon két zárda a fekete barátok és a szürke barátok részére. Ugyanakkor a királynő a kolozsvári iskola részére százforintos alapot létesített, és nemsokára az iskola fenntartására adományozta a kolozsvári terület dézsmájának negyedét. Ennek emlékét az óvári templom ajtaja fölé és a tanácsházban elhelyezett, kőbe vésett, alábbi felirat is megörökítette:
<p>"Királyi adomány vagyok: ennek az iskolának és a szegényeknek az öröksége; aki ezt és ehhez hasonló javaimat más célra fordítja, az töröltessék az élők könyvéből és az emberek emlékezetéből. Az Úrnak 1557. esztendejében".
<p>Két év múlva, 1559-ben, Izabella meghalt és János Zsigmond Gyulafehérváron kelt alapítólevelében, 1562. szeptember elsején megerősíti és kibővíti az adománylevelet. Ebben, hivatkozva a korábbi határozatokra, királyi tisztségénél fogva méltónak tartja, hogy az említett iskolákat tisztességes "jövedelmekkel felékesítse és gazdagítsa." Ezért Kolozsváron az ifjúság tanulmányainak előmozdítására, a szegények és az árvák felsegélyezésére, a "kolozsvári dézsma negyedét, a maga egészében", mind a bor, a gabona és "egyéb dolgok" negyedét a kolozsvári iskolának adományozza. Az alapítólevél megjelöli annak évi pénzbeli értékét (250 közönséges forint), és meghatározza a dézsmanegyed (quarta) további felosztását, mégpedig: egy-ötöde a szegények és az árvák fenntartására (50 forint), négyötöde (200 forint) az iskola és a tanulóifjúság használatára, valamint tanulmányainak előmozdítására fordítandó. A János Zsigmondot követő  erdélyi fejedelmek az alapítólevelet megerősítették: Báthori István 1571. december 17-én, Báthori Kristóf 1576. május 2-án és Bethlen Gábor 1626. szeptember 1-én. 
<p>Itt említjük meg, hogy a dézsma másik negyedét már a régi királyok a kolozsvári plébánosnak adományozták, a fennmaradó kétnegyedét pedig Bethlen Gábor a Kolozsváron alapított református iskolának adta. 
<p>Ilyen módon Kolozsváron a domonkosok óvári zárdájában létesített iskola számára a szükséges anyagi alapok biztosítva voltak. Az épület átalakítását és a szükséges javítások elvégzését a városi tanács vállalta magára a saját költségén. A fejedelem viszont egy nagy, állítólag 30 ablakos termet építtetett: az Apollo palotát, amelyet a diákok Appellatiumnak neveztek. 

<h3><a name="#002">Az első évtizedek</a></h3>
<p>Ami az iskola felekezeti hovatartozását illeti, nyilvánvaló, kezdetben a reformáció egymást követő hullámainak, illetőleg a kolozsvári plébános, Dávid Ferenc reformátori pályafutásának megfelelően, először lutheránus, azután református (valószínűleg 1564-től) és végül, 1568-tól unitárius volt. 
<p>Mivel a későbbi zivataros időkben az iskola korai irattára csaknem teljesen elpusztult, az intézet első korszakának belső rendjét , tantervét nem ismerjük pontosan. Tény azonban, hogy vezetői és tanárai Németországban tanultak, ezért joggal feltételezhetjük, hogy a német protestáns iskolák rendszerét, a Melanchtontól bevezetett iskolatípust követte. Ez annál valószínűbb, mivel a brassói Honterus iskola, amelyet a század negyvenes éveiben alapítottak, szintén ezt a típust tartotta szem előtt.
<p>Az úgynevezett protestáns humanista iskolák három fokozatra és nyolc csoportra tagolódtak, és a csoportok számozása felülről lefelé haladt, tehát a nyolcas csoport a kezdő tanulókat foglalta magában. Ebben a tanuló az írás, olvasás és a számolás elemeit sajátította el. A középső fokozat 7., 6., 5. és 4. csoportja a grammatikai oktatást biztosította, és a fő cél a latin nyelv alapos elsajátítása volt. A 3. csoportban Catót és Iszokratészt, a 2.-ban Cicerót, Erasmust és Melanchton kisebb grammatikáját tanulmányozták. A harmadik fokozat, vagyis az első csoport poétikát, retorikát és teológiát tanult, a szerzők közül Vergilius, Ovidius, Homérosz, a prózaírók közül Cicero, Plutarkhosz, Aiszóposz szerepeltek többek között. Végeredményben, a vallásoktatás mellett, a latin és görög szerzők megismerése és főként a latin nyelv elsajátítása volt az oktatás fő célja. 
<p>Ami a kolozsvári iskolát illeti, egy 1694-ből származó feljegyzés a parvistákat, etimologistákat, szintaxistákat, poétákat, rétorokat és a logikusokat említi. Az elemistáknak megfelelő parvisták az írást, olvasást és a számolást sajátították el, az etimológisták -szónyomozók- a latin nyelv alapjait, a szintaxisták a latin mondattan szabályait, a többiek pedig a nevüknek megfelelő tárgyakat tanulmányozták. 
<p>A két legidősebb csoport közül a tógások a papi pályára, a nemes ifjak közül kikerülő secundanusok világi pályára készültek. A harmadik fokozat elvégzése után sokan folytatták tanulmányaikat külföldi egyetemeken. 
<p>Az iskolát rector scholae (rektor) irányította, s neki két-három, ritkán négy lektor-tanár segédkezett. A kisebb diákokat a nagyobbak közül választott és javadalmazásban részesülő munkatársak - a collaboratorok tanították. A zenét a cantor (kántor) tanította, ő vezette az iskola- és csoportkórusokat. A tanítás reggel korán, rendszerint 5 órakor, énekléssel és imával kezdődött, ezután a rektor filozófiát és teológiát adott elő. Az lektorok órarendjében az idősebbeknek választási joguk volt. A kántor 12-től 13-ig tartotta óráit. Az egyes csoportokon belül minden "szaktárgyat" ugyanaz a lektor tanította. A collaboratorok de. 9 és du. 4 óra között tanítottak. 
<p>A tantervek és a tantárgyak természetesen korok szerint változtak, és idővel újabb és újabb diszciplínákkal bővültek, mint például matematika, egyetemes történelem, földrajz stb., de a felekezeti jellegének megfelelően valláserkölcsi nevelés és az ún. szépművészetek, amint az iskola régi felirata jelzi - musis et virtutibus -, maradtak a didaktikai és pedagógiai célkitűzés alapelvei. 
<p>Különösen a XVI. század második felében lett Kolozsvár az európai műveltség egyik jól ismert központja. A "Szamos-parti Athénben" gyakran megfordultak haladó gondolkozású tudósok és reformátorok: németek, olaszok és lengyelek. Többen közülük, mint például Sommer János, Oalaeologus Jakab, Francken Keresztély, az iskola rektorai vagy lektorai lettek. Életük valóságos regény, gyakran üldözőik elől menekülve kerestek menedéket Erdélyben, ahol egyes főurak, különösen a Gerendiek, szívesen befogadták őket. Valamennyien felvilágosult gondolkodók, termékeny írók voltak, akik műveiket Svájcban, Német- és Lengyelországban, vagy éppen Kolozsváron, Heltai Gáspár nyomdájában adták ki. 
<p>Az iskola első rektora a kor egyik legmarkánsabb személyisége, Dávid Ferenc volt. Nagy elfoglaltsága miatt Basilius Istvánt vette maga mellé, hogy irányítása alatt intézze az iskola ügyes-bajos dolgait. Az iskola rektora nemsokára a II. Rudolf császár prágai udvarával is szoros kapcsolatot tartó Sommer János lett. Sommer Heraclides moldvai vajda támogatásával az első moldvai latin - a Cotnari-i - iskola megalapítója lett, és jelentős kultúrtörténeti szerepet töltött be ebben a román fejedelemségben . A vajda bukása után Erdélybe menekült, és itt először a brassói, majd a besztercei iskola rektora lett (1571-1573). Dávid Ferenc vejeként nagy buzgalommal, szóban és írásban terjesztette a "kolozsvári vallást".Néhány kéziratos műve a kollégium egykori könyvtárában is fennmaradt. Pestisben halt meg 1573-ban, Kolozsváron.
<p>Utóda Palaeologus Jakab, korának egyik legnagyobb humanistája, aki nemcsak az erdélyi, hanem a cseh- és lengyelországi művelődésnek is egyik jelentős személyisége. Hosszabb ideig a Gerendi testvéreknél tartózkodott Alcinán, ahol leánya Despina meghalt. Két évig volt az iskolai rektora. Alapos görög tudásáért Dávid Ferenc egy új szellemű biblia fordításának akarta megnyerni. Kolozsvárról azonban csakhamar menekülnie kellett, mert a jezsuiták az inkvizició kezére akarták juttatni. Prágába ment és tíz év múlva, 1585. május 23-án, Rómában tűzhalállal végezték ki. Az utóbbi években, különösen Lengyel-, Cseh- és Olaszországban, a történeti kutatás nagy érdeklődést tanusít Palaeologus élete, tevékenysége és művei iránt.
<p>A korszak többi rektora és lektora közül éppen csak megemlítjük a nagy diplomáciai érzékkel rendelkező Hunyadi Demetert, a költő Bogáti Fazakas Miklóst, a humanizmus hazai történetében is számon tartott Deidrich Györgyöt.
<p>1579-ben Báthori István, ekkor már lengyel király, Kolozsváron megalapította az első katolikus iskolát, majd az egyetemi fokú akadémiát. Ennek vezetésével a Kolozsmonostorra betelepített jezsuitákat bízta meg. A jezsuiták jól felkészült és a leghatásosabb módszereket alkalmazó, harcos nevelők voltak, és csakhamar Kolozsváron is akkora hírnévre tettek szert, hogy a protestáns nemesek is szívesen küldték gyermekeiket iskolájukba. A város lakossága túlnyomó többsége unitárius lévén, érthetően nem szívesen fogadta az új tanítókat, és csakhamar ellentét támadt a két iskola között. Úgy véljük, hogy az újabb kutatások nagyobb fényt vethetnek ennek, valamint a később kirobbanó nyílt ellenségeskedésnek az okaira.
<p>1583 végén az egyik szász származású jezsuita tanár, Peter Frieschbier (Saxo) csatlakozott a kolozsvári valláshoz, és az unitárius iskola lektora lett. "Egyben egy sereg tanulót is elvont a jezsuita kollégiumtól, mivel ezek követték tanítójukat az unitárius iskolába. Érthető hát, hogy a jezsuiták mindenáron el akarták távolítani Frieschbiert Kolozsvárról" - állapítja meg a kérdés egyik lengyel kutatója. A városi tanács hallgatagon ellenállt követelésüknek. Friescbier egyelőre eltávozott a városból, de 1585 áprilisában visszatért és az unitárius iskola rektora lett. 
<p>Nem kevésbé izgatta a kedélyeket a brandenburgi származású Franeken Keresztély. Õ is a jezsuita rend tagjaként nevelkedett Rómában, majd Lengyelországba ment, és mivel a hitelvekben 
<p>is a rációt tartotta legfőbb értékmérőnek, a rendből kilépett, és a Gerendiekhez menekült Erdélybe. Tőlük lektornak hívták meg az unitáriusok iskolájába. Ebben a minőségben adta ki Heltai nyomdájában Epiktétosz latin fordítását, ami a saját és az iskola humanista szellemét tükrözi. A jezsuiták azonban kieszközölték mindkét aposztata üldözését és lefogását, de mielőtt ez megtörtént volna, ők elhagyták Kolozsvárt. Franeken Lengyelországba tért vissza és kibékült a renddel, de 1589 februárjában ismét a kolozsvári iskola lektoraként tünt fel. Két év múlva Gyulafehérváron "nyilvánosan megbánta eretnek bűneit", ami most az unitáriusok között keltett felháborodást. Meg- és áttérései ellenére, 1593-ban Heltai nyomdájának egy unitárius szellemű művet, a Disputatió-t adta ki, egy képzelt dialógust a teológusok és a filozófusok között. 
<p>Az ilyen megnyilvánulások és a századvégi gyakori politikai változások, különösen Básta szomorú szereplése, aki üldözte az unitáriusokat, majd a város ostroma Székely Mózes által olyan jezsuita-ellenes hangulatot teremtett, hogy 1603-ban a jezsuitáknak távozniuk kellett a városból, és a kiűzésükben az iskola tanulói is részt vettek, ami egyáltalán nem vált dicsőségükre.

<h3><a name="#003">A XVII. század</a></h3>
<p>Az iskola lendületes kezdeti fejlődését hosszabb ideig tartó visszaesés váltotta fel, ami nem annyira belső, mint inkább külső tényezőkkel magyarázható. A Báthoriakat követő fejedelmek megtartották ugyan a törvénybe iktatott vallásszabadságot, de elsősorban a református iskolákat támogatták, aminek eredményeként különösen a gyulafehérvári és a kolozsvári református iskola virágzott fel.
<p>Az unitáriusok helyzetét nehezítette a szombatos vallás elterjedése, melyet az unitárizmus hajtásának tekintettek. Ezért azután nemcsak állandó ellenőrzéssel s bizonyos hittételek rájuk kényszerítésével zaklatták őket, hanem a könykiadást is előzetes engedélyhez kötötték. Mindebből az iskolának is számos hátránya támadt, bár mindennapi munkáját zavartalanul folytathatta, sőt a könyvkiadás módját is megtalálta. A Heltai-nyomda már megkopott, de a lelkes Makai Nyíró János megtanulta a betűmetszést, új betűkkel látta el a nyomdát, és a többek között latin, magyar és német nyelven adta ki Cato bölcs mondásait, ami a városban is uralkodó tényleges helyzetet tükrözi. 
<p>A szász unitáriusok közül többen a hatalom vonzásának is engedve, áttértek a református vallásra, és 1628-ban Bethlen Gábor az Appellatiumot nekik engedte át templomozás céljából.
<p>A tanrendszer a XVI. századhoz képest nem sokat változott. A latin nyelv elsajátítása, a szabad művészetek ápolása, vallási kérdésekben a racionalizmushoz való ragaszkodás továbbra is a nevelés megvalósítandó célja maradt. E korszak rektorai közül a Svájcban, Német- és Francia- és Olaszországban tanult, igen gazdag irodalmi és tudományos munkát kifejtő Enyedi György, a tanulmányait Padovában végző Göcs Pál, a danzigi származású Radicius Bálint voltak a legkiválóbbak; a lektorok közül Járai Sámuel és a sokszor meghurcolt Árkosi Gelei Benedek. Mivel 1660-ban a lengyel szociniánusok közül azokat, akik ragaszkodtak vallásukhoz, kiűzték hazájukból és sokan közülük Erdélyben s éppen Kolozsváron telepedtek meg, ezért a XVII. század második felétől kezdve aránylag sok lengyel származású lektort találunk a tantestületben.

<h3><a name="#004">Küzdelmes évek</a></h3>
<p>Az önálló erdélyi fejedelemség megszűnésének átmeneti szakasza és a XVIII. század első fele a megpróbáltatások korát jelentette az iskola történetében. Ma is csodálattal és elismeréssel emlékezhetünk vissza arra a hősi magatartásra, amellyel az iskola tanulói, tanárai és természetesen az erdélyi unitáriusok védték a művelődésnek ezt a szerény, de számukra felmérhetetlen értékű intézményét.
<p>A Habsburgok uralma a híres Leopoldi diploma kiadásával kezdődött el, amely elvileg biztosította ugyan a korábbi szabadságjogokat és kiváltságokat, és a katolikus vallást is méltán - de nem méltó módszerekkel - igyekezett visszaállítani elvesztett jogaiba. Kolozsváron 1693. október 10-én, bizonyos anyagi kárpótlás ellenében, elvették az óvári iskolát, és a tanulóifjúság a piac nyugati oldalán kapott három, iskolai célokra alig alkalmas magánházat. 1695 - 1697 között, részben e házak átalakításával, részben pedig új helyiségek építésével, az iskola végre megfelelő épületekhez jutott.  
<p>Az építkezés még be sem fejeződött, amikor 1697. május 6-án a városban iszonyú tűz támadt, amely az egykori feljegyzések szerint "három templommal, két scholával, toronnyal együtt, a városnak nagyobb részét elpusztította úgy, hogy harmada, ha megmaradt".
<p>Mivel ismét építkezni kellett, és pénz nem volt, az iskola rektorát, Kolozsvári Dimén Pált Hollandiába küldték építési segély gyűjtésére. Dimén nem remélt nagy összeget, több mint 17 ezer forinttal tért vissza, ami azután elegendő volt a tűzkárok rendbehozására. Az egykori feljegyzések beszámolnak a város és az iskola nehéz helyzetéről a Rákóczi Ferenc vezette szabadságharc idején. Sok diák a kurucokhoz szökött át, nem volt biztosítva az ellátás, a tanulóifjúságot őrségekbe szervezték, de a közmondás ellenére a fegyverek között sem hallgattak el a múzsák, és a tanítás, megcsappant létszámmal ugyan, de tovább folyt. Az egyik korabeli feljegyzés elmondja, hogy 1708. július 19-én 40 diák aratni ment a rektornak, munkájukat azonban a kurucok megzavarták, és hármat közülük elfogtak, de hosszú alkudozások után szabadon engedték. A rektor és a lektorok, úgy látszik gyakran vették igénybe a diákokat mezei munkára, mert 1725-ben a konzisztórium a következő határozatot hozta: "A scholamesterek tanítványaikat paraszti magok munkájára, mezei robotára, marhák körül való forgolódásra, favágásra, vízhordásra nullo sub praetextu applikálni ne merészeljenek sub poena fl. 3, hogy a tanulástól el ne vonassanak."
<p>A Rákóczi-szabadságharc befejezése után új politikai helyzet alakult ki, és a császári udvar minden eszközt felhasznált a protestánsok visszaszorítására. Steinville tábornok katonái 1716-ban elvették a nagypiaci (a mostani főtér) templomot, ekkor a benne elhelyezett könyvnyomda és iskolai könyvtár is elpusztult. Két év múlva a piaci iskolát javaival együtt minden kárpótlás nélkül elvették, és 1718. április 2-án, a rektor és két lektor vigasztaló és buzdító szavai után a reményét vesztett ifjúság közül ki-ki a városban szerzett lakására vonult vissza. A kilátástalan helyzet ellenére a vezetőség aránylag rövid idő alatt megtalálta a szükséges megoldást. Már május elsején az iskola kiváló lektora, Szent Ábrahámi Mihály értesítette a dispersa iuventust - a szétszéledt ifjúságot -, hogy a tanítás a Bel-Magyar utcában átengedett ház négy földszinti és két emeleti termében megkezdődik. Szent-Ábrahámi Mihály iskolai pályáját két új tantárgy, a jog és a földrajz bevezetésével kezdte meg. Dimén halála után, 1720-ban, mint külföldön (Hollandiában és Németországban) tanult ifjú, ő vette át az iskola vezetését. Mivel az anyagi alapokat elvették, ő látta el a collaboratorok segítségével a lektorok feladatait is. Átszervezte az iskola egész rendjét, új szabályok bevezetésével helyreállította a meglazult fegyelmet, ő tiltotta el például a dohányzást, a herba nicotinianá-nak a használatát, és bizonyos mértékben korlátozta a diákgyűlés - coetus - hatáskörét. Hogy a tanulók alapos felkészülését biztosítsa, több tárgyból, - számtanból, logikából, földrajzból, világ- és egyháztörténetből, hittanból - tankönyvet írt.

<h3><a name="#005">Az iskola belső rendje</a></h3>
<p>Az iskola belső életéről értékes adatokat tartalmaznak azok a rendszeresen vezetett feljegyzések, amelyek az anyagi számadások mellett a fontosabbnak tartott eseményekről is beszámolnak. 1626-tól kezdődően - kisebb-nagyobb megszakításokkal a múlt század közepéig - külön naplóba az ún. Fasciulus Rerum Scholasticariumba vezették. Kiderül belőle a tanulók küzdelme, meg nem szűnő tevékenysége az anyagiak biztosítására. Ez a tevékenység nagyon változatos volt: énekeltek a temetéseken, üdvözlő szavakat, verseket mondtak és énekeltek a lakodalmakon és a vendégségeken, karácsonykor csoportokba szerveződve "kántáltak" a gazdagabb polgárok házainál, elmentek legációra, virrasztottak a betegek ágyainál, "asszisztáltak" az ünnepi szertartásokon, magántanítást vállaltak, és nem vonakodtak a mezei munkától: kapálástól, aratástól. kaszálástól, szénagyűjtéstől. A begyűlt összegeket időről időre szétosztották, elsősorban a rászoruló tanulók között.
<p>Életüket az iskolában és a bentlakásban maguk irányították. A diákgyűlés gondoskodott a fegyelem magatartásáról, a kihágások, vétségek számbavételéről és szigorú megbüntetéséről. A büntetést, akárcsak más iskolákban is - mai fogalmaink szerint - a túlzott szigorúság jellemezte. Ide tartozott a koplaltatás, kikötés, bebörtönzés és a kicsapás; az alsóbb csoportoknál a vesszőzés. Sajátos büntetési forma volt a plága, melynek célja a latin nyelv alapos elsajátítása. Minden csoport egyik tagjának a lektor nádpálcát  - plágát - adott át, aki annak adta tovább, akit anyanyelvén hallott beszélni. Ha a plága több mint két napig maradt nála, akkor régebben egy nummus (pénz) bírságot fizetett, később 12 sor latin verset, vagy ennek megfelelő prózát kellett megtanulnia, vagy 12 mondatot a bibliából. Alkalmazásának utolsó szakaszában ismét a pénzbírságra tértek át. A verés sem volt ritka fegyelmezési módszer; hogy "a gyermekeket kézzel vagy bottal ne verjék ... csak pálcával, 3 frt. büntetés mellett".
<p>A felsőosztályosok felszabadultak a pálca uralma alól, és mint tógások vagy secundanusok külön szervezetbe - coetusba - tömörültek. Az önkormányzati rendszer érvényesítésére a diákság valóságos "tisztviselői kart" választott, melynek minden tagja feladatának tartotta a hagyomány megőrzését és alkalmazását. Külön szervezet volt az "esküdtszék", amely kivizsgált és megbüntetett minden fegyelmi kihágást. A múlt század második felében Benczédi Gergely felújította ezt az intézményt, és 1947-ben új alapokra helyezve mi is alkalmaztuk, és örömmel állapíthattuk meg, hogy működése eredményesebb és hathatósabb volt, mint az igazgató vagy a tantestület fegyelmezése. 
<p>A diákság életéből természetesen nem hiányzott a szórakozás sem, és a hét bizonyos délutánjait szabadtéri játékokkal töltötte, ahogy ma mondanánk: "a sportnak szentelte", és sok gondot fordított a színjátszásra. A színjátszás irányítása a rektor és a senior hatáskörébe tartozott. 1572 áprilisában előadták Válaszúti György, az iskola seniorának darabját, A debreceni disputát, talán ez az első magyar nyelvű iskolai színjáték, amelynek előadásáról adatunk van. 1626. március 21-én Bethlen Gábor fejedelem és kísérete is részt vett az iskola egyik színielőadásán. Ma már több darab címét vagy éppen kéziratát ismerjük, s feltehető, hogy még nem egy lappang különböző könyvtárainkban.

<h3><a name="#006">Az iskola a XVIII. században és a reformkorban</a></h3>
<p>A sebtében átalakított magánház csakhamar nem volt elegendő a tanulók befogadására. Ezért ők maguk építettek agyaggal döngölt sövényfalakból új helyiségeket: 1726-ban ugyancsak négyet. Az alapítványi vagyon elvétele után az egyetemes egyház gyűjtésekből tartotta fenn az iskolát, annál is inkább, mert 1724-től kezdve az iskola fenntartása az egyházközségtől az egyetemes egyház hatáskörébe ment át. A gyűjtések nem jártak mindig kellő eredménnyel, s ilyenkor a tantestület fizetése és a tanulók segélyezése elmaradt. Közben a felekezet tagjai előtt bezárulnak a közhivatalok is, és a főurak néhány kivételével, más vallásra tértek. A megmaradottak különösen a Sukiak és a Petrichevich-Horváthok a szó szoros értelmében "táplálták a tanárokat és a tanulókat". A gyűjtések és adományozások folytán mégis akkora összeg gyűlt össze, hogy 1780-ra az iskolát egy emeletig felépítették, 1806-ban pedig befejezhették a második emelet építését is. Így épült fel a "régi kollégium", amely összesen 30 helyiséget foglalt magában. A termek számmal és külön névvel voltak jelölve, például "Róma", "Dézsmacsűr" stb. Ilyen módon az iskola épületének kérdése csaknem egy évszázadra megoldódott.
<p>A XVIII. század folyamán a felvilágosodás szelleme, ha lassan is, éreztette hatását. Mária Terézia 1777-ben kiadta a tanítás egységes rendszerét és szellemét megkívánó rendeletet, a Ratio educationist. Magas követelményeinek azonban az erdélyi iskolák nem tudtak eleget tenni, ezért II. József 1782-ben Erdélyben bevezeti az ún. Norma regiát, amely csökkentette a Ratio túlzsúfolt tantervét, és a hangsúlyt az irodalmi és az esztétikai nevelésre helyezte. Az erdélyi iskolák ennek alkalmazásától is idegenkedtek, mert belügyeikbe való beleszólásnak tekintették. Néhány hónappal később megjelent a Türelmi rendelet, amely a felvilágosodás szellemében bizonyos enyhítéseket hozott, sőt az iskolának 63 évvel korábban elvett javaiért II. József  5000 forint kárpótlást adott. Az így megindult folyamat kedvező légkört teremtett, mert elkerülhetetlenül a vallásszabadság és az alkotmányosság helyreállítása felé haladt, ami lehetővé tette az iskolában is a reformok egymás utáni alkalmazását. 
<p>A tárgyalt korszak igazgatói és tanárai közül messze kimagaslik Szent Ábrahámi Mihály, Ágh István, a jobbágyszármazású szülőktől származó Lázár István, a későbbi püspök, a költő és történész Székely Sándor, a "Vadrózsák" gyűjtője, Kriza János, a jogtudós Mikó Lőrinc és mindenek előtt Brassai Sámuel, aki két ízben is betöltötte az igazgatói tisztet (1838-1840 és 1845-1847 között). 
<p>Nincs helyünk kitérni itt mindazokra a tantervi és módszertani változásokra, amelyek a nevelést és az oktatást összhangba hozták az idők követelményeivel. Néhányat azonban mégsem mellőzhetünk: megváltoztak a tantestület címei: a rektorból igazgató, azaz tanár lett; új tantárgyak kerültek be a tantervbe; elmaradtak a régi középkorias szokások, a diákgyűlés hatáskörét mindinkább az igazgató vette át; korszerűsödött a tanterv, és a szabadelvű eszmék úgy otthonra találtak a múzsáknak ebben a hajlékában, mint a XVI. században a racionalizmus dogmaellenessége.
<p>Az iskola didaktikai, pedagógiai, szellemi fejlődését nagymértékben előmozdította Brassai Sámuel. 1837-ben már mint ismert tudós lett az iskola tanára, s azt a feladatot kapta, hogy új, a követelményeknek jobban megfelelő tantervet dolgozzon ki. Tantervében Brassai csaknem teljes mértékben szakított az évszázados hagyományos felfogással, és a latin nyelv uralmát megdöntve az anyanyelvi oktatást vezette be. A csoportrendszert a szakrendszerrel helyettesítette, vagyis a tanár nem egy egész csoportot tanított mindenből, hanem egy vagy két tárgyat minden vagy legalábbis a legtöbb csoportban. Nyilván, ez a tantestület szűkebb szakosítását, de alaposabb felkészülését kívánta meg. A csoportokat osztályokkal cserélte fel, és ezek számozását alulról felfelé jelölte. Az oktatás elmélyítésére megkövetelte a tankönyvek rendszeres használatát, és ő maga hét tankönyvet írt. Az esztétikai és irodalmi oktatás mellett a korábban elhanyagolt reáltudományok: a matematika, fizika, természettan, ásványtan, növénytan alaposabb művelését is megkívánta, és nagy súlyt helyezett a szertárak rendszeres gyarapítására.
<p>Brassai tervének gyakorlatba ültetésével az iskola nagy lépést tett előre, és sok tekintetben az erdélyi nevelés élvonalába került.
<p>A reformkor más újításokat is hozott: különvált a teológiai tanfolyam, előbb két-, majd három-, végül négyéves időtartammal önálló akadémiává fejlődött. 1847-ben jogtudományi tanszéket is létesítettek, de az alapítvány megsemmisülése miatt ez csak egy évig működhetett.

<h3><a name="#007">1848 és az azt követő időszak</a></h3>
<p>Az 1848-as szabadságharc idején az iskola épületét katonai kórháznak foglalták le, és a tanulók nagy része bevonult katonának, ezért a tanítás egy ideig szünetelt. A forradalmi harc bukása után az erdélyi helytartóság elismerte az iskola működési jogát, sőt főgimnáziumnak nyilvánította, a jogi tanfolyamot megszüntette, és a filozófiát beolvasztotta a főgimnáziumi 
<p>tantervbe. Az új nevelésügyi rendelet, az Entwurf  biztosította az állam ellenőrzési jogát az iskolák fölött. Ekkor jött létre a főgimnázium, amely négy alsó osztályú gimnáziumból és a filozófiát kurzust egységesítő négy felső osztályból állott.
<p>Az Entwurf az erdélyi iskolákban határozott ellenkezést váltott ki. 1860-ban ebbe az iskolába látszólag annak a szellemében, de a valóságban a Brassai-tantervnek megfelelő rendszert vezettek be. Ezzel indul meg az a folyamat, amely az iskolát mindinkább modernizálja és színvonalassá teszi. A folyamatot előmozdító számos ok közül csak néhányat említünk meg:
<p>A szabadelvűség fokozatos fejlődése lassanként feloldotta az unitáriusok iránt különösen a magasabb körökben táplált előítéletet. Ennek szétoszlatásához nem kis mértékben járult hozzá az a tény, hogy "felfedeződtek" az angol hitrokonok, akik már az abszolutizmus éveiben hathatós segítséget nyújtottak. A megváltozott hangulat eredménye az iskola számára az lett, hogy más felekezetű és nemzetiségű tanulók: románok, németek, főképpen zsidók egyre nagyobb számban látogatták. Ennek szemléltetésére csak egy példát hozunk fel: 1913-14-ben a tanulók száma a nyolc osztályban 344, ebből 128, vagyis több mint egyharmad más vallású.
<p>Fejlődését elősegítette a kolozsvári egyetem létesítése 1872-ben, amely biztosítani tudta a tantestület megfelelő utánpótlását. Az iskola korábban is arra törekedett, hogy az alapítólevélnek megfelelően "tudós és nyelvekben jártas tanárokat" alkalmazzon. A rektor és legtöbbször a tanárok is külföldön: olasz, holland és német egyetemeken tanultak, majd 1860-tól az angol főiskolákon létesítettek ösztöndíjakat számukra. A kolozsvári egyetem alapítása nyomán a külföldi tanulmányok nem maradtak el, de a megnövekedett tantestület valamennyi tagja alapos képzésben részesülhetett. 
<p>E korszak igazgatói és tanárai közül csak a legkiválóbbakat említhetjük meg: a gazdag publicisztikai tevékenységet is kifejtő Nagy Lajost, a már Angliában tanulmányokat folytató Benczédi Gergelyt és Kovács Jánost, az iskola történetének alapos kutatóját és ismerőjét, Gál Kelement, a tanárok közül Simén Domokost, Kanyaró Ferencet, Uzoni Fosztó Gábort, Pálfi Mártont, Nyiredy Gézát, Kelemen Lajost, Varga Bélát, Gelei Józsefet, Borbély Istvánt, akik mind didaktikai, mind pedig irodalmi vagy tudományos munkásságukkal általános elismerést váltottak ki. 
<p>Nem kis mértékben járultak hozzá az iskola fellendüléséhez a nagylelkű adakozók. Közöttük első helyen Berde Mózes áll, aki 1888 szeptemberében kelt végrendeletében csaknem egymillió értékű vagyont hagyott egyházának, s ebből százezer forintot a kolozsvári iskola számára, mert amint írta: "Kora ifjúságomból szívem egy érzést, agyam egy gondolatot táplált: felsegíteni szegény vallás közösségemet, könnyíteni az utat a tanuló fiatalságnak a tudományok megszerzésére és segélyezni elhagyott szolgáit és tanárait". Az adományozások tették lehetővé a könyvtárak, szertárak gyarapítását. Már a XVIII. században a külföldre küldött ifjak kötelezték magukat, hogy könyveket vásárolnak, és idővel azokat az iskolának adományozzák. Bölöni Farkas Sándor, Brassai Sámuel és sokan mások könyvtárukat adományozták az iskolának.
<p>Lassanként olyan anyagi alapok gyűltek össze, amelyek 1897-ben lehetővé tették a mostani iskola felépítésének megkezdését, amely Pákei Lajos tervei szerint négy év alatt készült el. Az épületet 1901. szeptember 21-én ünnepélyes megnyitó keretében adták át rendeltetésének Erdély egyik legnagyobb s legszebb iskolaépületeként. Büszke volt rá minden tanulója, tanára s 
talán Kolozsvár valamennyi lakója. Nicolae Iorga, a nagy román történész, amikor a húszas években felkereste Kolozsvárt, azt írta róla, hogy egyetemnek beillő, valóságos palota.
<p>A későbbi fejlődés már mindannyiunk előtt ismert. Erdélynek Romániával való egyesülése után mint felekezeti iskola államsegélyben ugyan nem részesült, de szabadon működhetett, és mint néhány évszázadon át, a hívek adakozása lehetővé tette az anyagi alapok biztosítását. A második világháború zivatarában ágyúgolyó-találat érte, de a főhatóság és az iskola vezetősége rövid idő alatt nemcsak a keletkezett rongálódásokat javíttatta ki, hanem az épület általános rendbetételére számottevő anyagi áldozatot hozott. A második világháború után az állam megkülönböztetés nélkül biztosította a felekezeti iskolák tantestületének fizetését, a tanári kar igazódott az új követelményekhez, és a háború okozta nehézségek ellenére a tanítás zavartalanul, megnövekedett létszámmal folyt.
	
<h3><a name="#008">Az iskola az államosítás után</a></h3>
<p>Az 1948 augusztusában életbe lépett tanügyi reform teljesen új alapokra helyezte a hazai oktatást. Az iskola minden fokon az állam fenntartása, irányítása és ellenőrzése alá került. A reform az egész ifjúság nemre, vallásra és nemzetiségre való tekintet nélkül, egységes nevelését és oktatását tűzte ki célul.
<p>Hosszú történetének ezt a szakaszát dr. Gaál Györgynek, az iskola 1991 - 1992. évi évkönyvében (5.-7.) közölt tanulmánya alapján ismertetjük.
<p>Az 1948. augusztusában államosított iskola az "1-es számú Magyar Fiúlíceum" nevet kapta és az egységes állami tantervek alapján, kitűnő tanári karral kezdett működni. Kétségtelen a város egyik legnagyobb és legjobb iskolája maradt, 1949-ben bevezették az esti tagozatot; az 1954-ben elrendelt új számozás folytán "7-es számú Líceum" lett. Fennállásának 400. évfordulója alkalmából 1957-ben, az illetékes felsőbb hatóságok engedélyével a "Brassai Sámuel Líceum" nevet vette fel. A magyarországi forradalmat követő politikai tisztogatások és koncepciós perek következtében 1957-ben több kiváló tanárát elbocsátották.
<p>1962-ben négy román osztály beindításával megalakul az esti líceumi román tagozat, amelynek élére aligazgatót állítottak; 1962-től pedig német tagozattal bővült. 1963-ban megtiltják a Brassai Sámuel név használatát, de hét év múlva, 1970-ben, államtanácsi határozattal ismét engedélyezik. 
<p>Az 1960-as évek végén és a következő évtized elején határozott fellendülés tapasztalható az iskola életében: megjelenik a "Fiatal szívvel" című diákfolyóirat, megszervezik a "Brassai Hetet" és a sportélet fellendítésére "Brassai Kupát" létesítenek (1980), különböző alapítványokat hoznak létre.
<p>1977-ben a Brassait, sok más iskolához hasonlóan, ipari líceumnak alakították át, ami sok tehetséges diák távozását vonta maga után. 1972-ben a német tagozatot a Cosbuc Líceumba helyezték át; 1985 őszétől kezdve pedig a nappali tagozaton is román tannyelvű osztályokat 
indítottak be. Mivel ezzel párhuzamosan a magyar osztályok számát csökkentették, a román osztályok tanulóinak jó része magyar anyanyelvű volt. Ugyanakkor a magyar feliratokat és a régi érettségi tablókat leszedették.
<p>Az 1989. decemberi változás után, - amint ez az 1990. január 19-iki felterjesztésből kitűnik - a közel 2500 tanulót számláló "iskolakombinát"-ból a nappali tagozat román tannyelvű osztályait az újonnan létesített "Avram Iancu" Líceumba költöztették át, kivéve azokat a diákokat, akik a magyar tagozatra iratkoztak át. Az esti román tagozat is az iskolában maradt ugyan, de mostantól kezdve az iskola ismét visszakapta magyar jellegét.
<p>A tanulók önképzését számos tudományos-, művészeti és sportkör biztosítja, amelyek a "Kriza János" Önképző Kör tagozatai. Iskolai lap jelenik meg évente négyszer. A "Brassai Kupa" elnyeréséért évenkénti sportversenyeket szerveznek.  

<b><i>(Bodor András: Iskolánk történetéből)</i></b>
<p>

<h3><a href="#009">A Brassai Sámuel Líceum 1985 után:</a></h3>
<p>1985-ben létesül a Bogáncs néptáncegyüttes, táncházmozgalom indul a Brassaiban az akkor oda került Tolna Éva tanárnő vezetésével
<p>1990-ben Zwolle-ból a Carolus Clusius iskola vezetősége keresi fel az iskolát, egyúttal segélyszállítmányt hoznak. A látogatás eredményeképpen a két intézmény testvériskolai kapcsolatba kerül.  
<p>1990-ben bejegyzik hivatalos jogi személynek a Brassais Véndiák Alapítványt, melynek Szabó Zsolt lesz az elnöke
<p>1990-ben egy soproni iskolával is testvériskolai kapcsolat alakul ki
<p>1993-ban a Brassais Véndiák Alapítvány Hantz Irén tanárnő javaslatára Torockón házat vesz. A házvételben Dr. Tobias Károly, valamint az iskola német, magyar, és holland barátai segítenek.  
<p>1993. szeptember 24-én avatják a Torockói Házat

<h4><a href="#000">Vissza</a></h4>
</div>
<?php  include("homefooter.inc.php");?>