<?PHP 
$SiteTitle="A kolozsvári Brassai Sámuel líceum története 1993-ig";
$SiteDescription="Az iskolánk története a XVI század és 1993 között";
include("homemenu.php"); 
?>

<h2 class="sub_title">Az iskolánk története</h2>

  <table style="width:100%;border-style:none;">
  <tr>
	<td>
		  <h3><a name="#000">Tartalom:</a></h3>
		  <ul>
		    <li><a href="#001">Elöszó</a>
			<li><a href="#001">Az iskola megalapítása</a>
		    <li><a href="#002">Az elsõ évtizedek</a>
		    <li><a href="#003">A XVII. század</a>
		    <li><a href="#004">Küzdelmes évek</a>	
		    <li><a href="#005">Az iskola belsõ rendje</a>	
		    <li><a href="#006">Az iskola a XVIII. században</a>	
		    <li><a href="#007">1848 és az azt követõ idõszak</a>	
		    <li><a href="#008">Az iskola az államosítás után</a>	
		    <li><a href="#009">A líceum 1985 után:</a>	
		  </ul>
	</td>
    <td><IMG src="images/ISKOLA.JPG" width="400" height="388" alt="Az iskola épülete"/><br/>
	  A felvétel 1963 ban készült.</td>
  </tr></TABLE>
<hr>
  
<h3><a href="#001">Elöszó</a></h3>
<p>A XVI. század második felében a reformáció, majd az ellenreformáció hatására az erdélyi iskoláztatás túljutott a korábbi szûk, városi vagy szerzetesi kereteken, és bár bizonyos csoportok, felekezetek szolgálatába állt, ezt úgy tette, hogy az egyházi és a világi értelmiség nevelésével az egész lakosság felemelkedését tartotta szem elõtt. Minden itteni iskola külön színt, helyi sajátosságot képviselt ugyan, de mert benne az európai mûveltség egyik vagy másik iránya érvényesült, annak felerõsítésével és továbbterjesztésével kapcsolódott, illetve bekapcsolta szûkebb hazánkat az egyetemes mûvelõdés nagy áramlataiba. 
<p>A mostani Brassai Sámuel Elméleti Líceum, az erdélyi unitáriusok egykori iskolája, nemcsak hazai, hanem európai viszonylatban is egyedülálló intézmény. A XVI század belsõ és külsõ, a reformációval kezdõdõ politikai, vallási és ideológiai harcainak légkörében született meg, s hogy évszázadokon át nem pusztult el, mint sok más akkor keletkezett intézmény, azt fenntartói áldozatkészségének, ragaszkodásának és az erdélyi szellemiségnek köszönhette.

<h3>Az iskola megalapítása</h3>
<p>Az iskolát a XVI. század közepén, a reformáció itteni terjeszkedésének korában, a független erdélyi fejedelemség kialakulásának idején alapították. A mohácsi vész után Erdély a két nagyhatalom: a Habsburg és a török birodalom terjeszkedési célja és ütközõ területe lett. Az évtizedekig tartó és sok nyomorúságot hozó versengés a török birodalom javára dõlt el, és 1556-ban Szapolyai János özvegye, Izabella, aki korábban az ország elhagyására kényszerült fiával, a törvényes trónörökössel, János Zsigmonddal együtt visszatért Erdélybe, és a Kolozsváron még abban az idõben megtartott országgyûlés úgy határozott, hogy mivel János Zsigmond még kiskorú: "nem tartható képesnek és alkalmasnak a kormányzásra, ezért öt éven át az ország vezetésének legfõbb hatalmát a királyné gyakorolja." Ugyanannak az országgyûlésnek egy másik határozata kimondta, hogy a "papi javak, valamint a székesegyházi adók egész Erdélyben szálljanak át a királyi kincstárra." E javak lefoglalásával együtt a szerzetesrendeket is feloszlatták, és a fekete barátokat az országból kitiltották, sõt a fehérvári katolikus püspök Bornemissza Pál is kénytelen volt elhagyni az országot. 
<p>Ezek az események hátrányosan befolyásolták az iskoláztatás helyzetét és annak teljes átszervezését tették szükségessé. Az 1557. február 6-15 között tartott gyulafehérvári országgyûlésen a karok és a rendek  szomorúan állapítják meg, hogy "az ifjúság nevelése elhanyagoltatott, és a mûveletlenség napról napra terebélyesedik és növekszik", ezért arra kérik a királynõt, hogy ezekben az ifjúságot "tudós és nyelvekben jártas férfiak kegyesen és biztonságosan neveljék". Kérésüket a királynõ méltányosnak tartotta, és a szerzetesek két kolostorát, a vásárhelyit és a kolozsvárit erre a célre kijelölte, amit "az ország urai tetszésnyilvánítással fogadtak" s köszönetüket és teljes hûségüket fejezték ki a királynõnek. 
<p>Öt hónap múlva a június 1-10 között tartott tordai országgyûlésen a királynõ véglegesen jóváhagyja, hogy "Kolozsváron a domonkosok zárdájában, Vásárhelyen a ferencesek zárdájában és  Váradon a mindszentek zárdájában iskolák állíttassanak fel", mégis úgy, hogy Váradon megmaradjon két zárda a fekete barátok és a szürke barátok részére. Ugyanakkor a királynõ a kolozsvári iskola részére százforintos alapot létesített, és nemsokára az iskola fenntartására adományozta a kolozsvári terület dézsmájának negyedét. Ennek emlékét az óvári templom ajtaja fölé és a tanácsházban elhelyezett, kõbe vésett, alábbi felirat is megörökítette:
<p>"Királyi adomány vagyok: ennek az iskolának és a szegényeknek az öröksége; aki ezt és ehhez hasonló javaimat más célra fordítja, az töröltessék az élõk könyvébõl és az emberek emlékezetébõl. Az Úrnak 1557. esztendejében".
<p>Két év múlva, 1559-ben, Izabella meghalt és János Zsigmond Gyulafehérváron kelt alapítólevelében, 1562. szeptember elsején megerõsíti és kibõvíti az adománylevelet. Ebben, hivatkozva a korábbi határozatokra, királyi tisztségénél fogva méltónak tartja, hogy az említett iskolákat tisztességes "jövedelmekkel felékesítse és gazdagítsa." Ezért Kolozsváron az ifjúság tanulmányainak elõmozdítására, a szegények és az árvák felsegélyezésére, a "kolozsvári dézsma negyedét, a maga egészében", mind a bor, a gabona és "egyéb dolgok" negyedét a kolozsvári iskolának adományozza. Az alapítólevél megjelöli annak évi pénzbeli értékét (250 közönséges forint), és meghatározza a dézsmanegyed (quarta) további felosztását, mégpedig: egy-ötöde a szegények és az árvák fenntartására (50 forint), négyötöde (200 forint) az iskola és a tanulóifjúság használatára, valamint tanulmányainak elõmozdítására fordítandó. A János Zsigmondot követõ  erdélyi fejedelmek az alapítólevelet megerõsítették: Báthori István 1571. december 17-én, Báthori Kristóf 1576. május 2-án és Bethlen Gábor 1626. szeptember 1-én. 
<p>Itt említjük meg, hogy a dézsma másik negyedét már a régi királyok a kolozsvári plébánosnak adományozták, a fennmaradó kétnegyedét pedig Bethlen Gábor a Kolozsváron alapított református iskolának adta. 
<p>Ilyen módon Kolozsváron a domonkosok óvári zárdájában létesített iskola számára a szükséges anyagi alapok biztosítva voltak. Az épület átalakítását és a szükséges javítások elvégzését a városi tanács vállalta magára a saját költségén. A fejedelem viszont egy nagy, állítólag 30 ablakos termet építtetett: az Apollo palotát, amelyet a diákok Appellatiumnak neveztek. 

<h3><a name="#002">Az elsõ évtizedek</a></h3>
<p>Ami az iskola felekezeti hovatartozását illeti, nyilvánvaló, kezdetben a reformáció egymást követõ hullámainak, illetõleg a kolozsvári plébános, Dávid Ferenc reformátori pályafutásának megfelelõen, elõször lutheránus, azután református (valószínûleg 1564-tõl) és végül, 1568-tól unitárius volt. 
<p>Mivel a késõbbi zivataros idõkben az iskola korai irattára csaknem teljesen elpusztult, az intézet elsõ korszakának belsõ rendjét , tantervét nem ismerjük pontosan. Tény azonban, hogy vezetõi és tanárai Németországban tanultak, ezért joggal feltételezhetjük, hogy a német protestáns iskolák rendszerét, a Melanchtontól bevezetett iskolatípust követte. Ez annál valószínûbb, mivel a brassói Honterus iskola, amelyet a század negyvenes éveiben alapítottak, szintén ezt a típust tartotta szem elõtt.
<p>Az úgynevezett protestáns humanista iskolák három fokozatra és nyolc csoportra tagolódtak, és a csoportok számozása felülrõl lefelé haladt, tehát a nyolcas csoport a kezdõ tanulókat foglalta magában. Ebben a tanuló az írás, olvasás és a számolás elemeit sajátította el. A középsõ fokozat 7., 6., 5. és 4. csoportja a grammatikai oktatást biztosította, és a fõ cél a latin nyelv alapos elsajátítása volt. A 3. csoportban Catót és Iszokratészt, a 2.-ban Cicerót, Erasmust és Melanchton kisebb grammatikáját tanulmányozták. A harmadik fokozat, vagyis az elsõ csoport poétikát, retorikát és teológiát tanult, a szerzõk közül Vergilius, Ovidius, Homérosz, a prózaírók közül Cicero, Plutarkhosz, Aiszóposz szerepeltek többek között. Végeredményben, a vallásoktatás mellett, a latin és görög szerzõk megismerése és fõként a latin nyelv elsajátítása volt az oktatás fõ célja. 
<p>Ami a kolozsvári iskolát illeti, egy 1694-bõl származó feljegyzés a parvistákat, etimologistákat, szintaxistákat, poétákat, rétorokat és a logikusokat említi. Az elemistáknak megfelelõ parvisták az írást, olvasást és a számolást sajátították el, az etimológisták -szónyomozók- a latin nyelv alapjait, a szintaxisták a latin mondattan szabályait, a többiek pedig a nevüknek megfelelõ tárgyakat tanulmányozták. 
<p>A két legidõsebb csoport közül a tógások a papi pályára, a nemes ifjak közül kikerülõ secundanusok világi pályára készültek. A harmadik fokozat elvégzése után sokan folytatták tanulmányaikat külföldi egyetemeken. 
<p>Az iskolát rector scholae (rektor) irányította, s neki két-három, ritkán négy lektor-tanár segédkezett. A kisebb diákokat a nagyobbak közül választott és javadalmazásban részesülõ munkatársak - a collaboratorok tanították. A zenét a cantor (kántor) tanította, õ vezette az iskola- és csoportkórusokat. A tanítás reggel korán, rendszerint 5 órakor, énekléssel és imával kezdõdött, ezután a rektor filozófiát és teológiát adott elõ. Az lektorok órarendjében az idõsebbeknek választási joguk volt. A kántor 12-tõl 13-ig tartotta óráit. Az egyes csoportokon belül minden "szaktárgyat" ugyanaz a lektor tanította. A collaboratorok de. 9 és du. 4 óra között tanítottak. 
<p>A tantervek és a tantárgyak természetesen korok szerint változtak, és idõvel újabb és újabb diszciplínákkal bõvültek, mint például matematika, egyetemes történelem, földrajz stb., de a felekezeti jellegének megfelelõen valláserkölcsi nevelés és az ún. szépmûvészetek, amint az iskola régi felirata jelzi - musis et virtutibus -, maradtak a didaktikai és pedagógiai célkitûzés alapelvei. 
<p>Különösen a XVI. század második felében lett Kolozsvár az európai mûveltség egyik jól ismert központja. A "Szamos-parti Athénben" gyakran megfordultak haladó gondolkozású tudósok és reformátorok: németek, olaszok és lengyelek. Többen közülük, mint például Sommer János, Oalaeologus Jakab, Francken Keresztély, az iskola rektorai vagy lektorai lettek. Életük valóságos regény, gyakran üldözõik elõl menekülve kerestek menedéket Erdélyben, ahol egyes fõurak, különösen a Gerendiek, szívesen befogadták õket. Valamennyien felvilágosult gondolkodók, termékeny írók voltak, akik mûveiket Svájcban, Német- és Lengyelországban, vagy éppen Kolozsváron, Heltai Gáspár nyomdájában adták ki. 
<p>Az iskola elsõ rektora a kor egyik legmarkánsabb személyisége, Dávid Ferenc volt. Nagy elfoglaltsága miatt Basilius Istvánt vette maga mellé, hogy irányítása alatt intézze az iskola ügyes-bajos dolgait. Az iskola rektora nemsokára a II. Rudolf császár prágai udvarával is szoros kapcsolatot tartó Sommer János lett. Sommer Heraclides moldvai vajda támogatásával az elsõ moldvai latin - a Cotnari-i - iskola megalapítója lett, és jelentõs kultúrtörténeti szerepet töltött be ebben a román fejedelemségben . A vajda bukása után Erdélybe menekült, és itt elõször a brassói, majd a besztercei iskola rektora lett (1571-1573). Dávid Ferenc vejeként nagy buzgalommal, szóban és írásban terjesztette a "kolozsvári vallást".Néhány kéziratos mûve a kollégium egykori könyvtárában is fennmaradt. Pestisben halt meg 1573-ban, Kolozsváron.
<p>Utóda Palaeologus Jakab, korának egyik legnagyobb humanistája, aki nemcsak az erdélyi, hanem a cseh- és lengyelországi mûvelõdésnek is egyik jelentõs személyisége. Hosszabb ideig a Gerendi testvéreknél tartózkodott Alcinán, ahol leánya Despina meghalt. Két évig volt az iskolai rektora. Alapos görög tudásáért Dávid Ferenc egy új szellemû biblia fordításának akarta megnyerni. Kolozsvárról azonban csakhamar menekülnie kellett, mert a jezsuiták az inkvizició kezére akarták juttatni. Prágába ment és tíz év múlva, 1585. május 23-án, Rómában tûzhalállal végezték ki. Az utóbbi években, különösen Lengyel-, Cseh- és Olaszországban, a történeti kutatás nagy érdeklõdést tanusít Palaeologus élete, tevékenysége és mûvei iránt.
<p>A korszak többi rektora és lektora közül éppen csak megemlítjük a nagy diplomáciai érzékkel rendelkezõ Hunyadi Demetert, a költõ Bogáti Fazakas Miklóst, a humanizmus hazai történetében is számon tartott Deidrich Györgyöt.
<p>1579-ben Báthori István, ekkor már lengyel király, Kolozsváron megalapította az elsõ katolikus iskolát, majd az egyetemi fokú akadémiát. Ennek vezetésével a Kolozsmonostorra betelepített jezsuitákat bízta meg. A jezsuiták jól felkészült és a leghatásosabb módszereket alkalmazó, harcos nevelõk voltak, és csakhamar Kolozsváron is akkora hírnévre tettek szert, hogy a protestáns nemesek is szívesen küldték gyermekeiket iskolájukba. A város lakossága túlnyomó többsége unitárius lévén, érthetõen nem szívesen fogadta az új tanítókat, és csakhamar ellentét támadt a két iskola között. Úgy véljük, hogy az újabb kutatások nagyobb fényt vethetnek ennek, valamint a késõbb kirobbanó nyílt ellenségeskedésnek az okaira.
<p>1583 végén az egyik szász származású jezsuita tanár, Peter Frieschbier (Saxo) csatlakozott a kolozsvári valláshoz, és az unitárius iskola lektora lett. "Egyben egy sereg tanulót is elvont a jezsuita kollégiumtól, mivel ezek követték tanítójukat az unitárius iskolába. Érthetõ hát, hogy a jezsuiták mindenáron el akarták távolítani Frieschbiert Kolozsvárról" - állapítja meg a kérdés egyik lengyel kutatója. A városi tanács hallgatagon ellenállt követelésüknek. Friescbier egyelõre eltávozott a városból, de 1585 áprilisában visszatért és az unitárius iskola rektora lett. 
<p>Nem kevésbé izgatta a kedélyeket a brandenburgi származású Franeken Keresztély. Õ is a jezsuita rend tagjaként nevelkedett Rómában, majd Lengyelországba ment, és mivel a hitelvekben 
<p>is a rációt tartotta legfõbb értékmérõnek, a rendbõl kilépett, és a Gerendiekhez menekült Erdélybe. Tõlük lektornak hívták meg az unitáriusok iskolájába. Ebben a minõségben adta ki Heltai nyomdájában Epiktétosz latin fordítását, ami a saját és az iskola humanista szellemét tükrözi. A jezsuiták azonban kieszközölték mindkét aposztata üldözését és lefogását, de mielõtt ez megtörtént volna, õk elhagyták Kolozsvárt. Franeken Lengyelországba tért vissza és kibékült a renddel, de 1589 februárjában ismét a kolozsvári iskola lektoraként tünt fel. Két év múlva Gyulafehérváron "nyilvánosan megbánta eretnek bûneit", ami most az unitáriusok között keltett felháborodást. Meg- és áttérései ellenére, 1593-ban Heltai nyomdájának egy unitárius szellemû mûvet, a Disputatió-t adta ki, egy képzelt dialógust a teológusok és a filozófusok között. 
<p>Az ilyen megnyilvánulások és a századvégi gyakori politikai változások, különösen Básta szomorú szereplése, aki üldözte az unitáriusokat, majd a város ostroma Székely Mózes által olyan jezsuita-ellenes hangulatot teremtett, hogy 1603-ban a jezsuitáknak távozniuk kellett a városból, és a kiûzésükben az iskola tanulói is részt vettek, ami egyáltalán nem vált dicsõségükre.

<h3><a name="#003">A XVII. század</a></h3>
<p>Az iskola lendületes kezdeti fejlõdését hosszabb ideig tartó visszaesés váltotta fel, ami nem annyira belsõ, mint inkább külsõ tényezõkkel magyarázható. A Báthoriakat követõ fejedelmek megtartották ugyan a törvénybe iktatott vallásszabadságot, de elsõsorban a református iskolákat támogatták, aminek eredményeként különösen a gyulafehérvári és a kolozsvári református iskola virágzott fel.
<p>Az unitáriusok helyzetét nehezítette a szombatos vallás elterjedése, melyet az unitárizmus hajtásának tekintettek. Ezért azután nemcsak állandó ellenõrzéssel s bizonyos hittételek rájuk kényszerítésével zaklatták õket, hanem a könykiadást is elõzetes engedélyhez kötötték. Mindebbõl az iskolának is számos hátránya támadt, bár mindennapi munkáját zavartalanul folytathatta, sõt a könyvkiadás módját is megtalálta. A Heltai-nyomda már megkopott, de a lelkes Makai Nyíró János megtanulta a betûmetszést, új betûkkel látta el a nyomdát, és a többek között latin, magyar és német nyelven adta ki Cato bölcs mondásait, ami a városban is uralkodó tényleges helyzetet tükrözi. 
<p>A szász unitáriusok közül többen a hatalom vonzásának is engedve, áttértek a református vallásra, és 1628-ban Bethlen Gábor az Appellatiumot nekik engedte át templomozás céljából.
<p>A tanrendszer a XVI. századhoz képest nem sokat változott. A latin nyelv elsajátítása, a szabad mûvészetek ápolása, vallási kérdésekben a racionalizmushoz való ragaszkodás továbbra is a nevelés megvalósítandó célja maradt. E korszak rektorai közül a Svájcban, Német- és Francia- és Olaszországban tanult, igen gazdag irodalmi és tudományos munkát kifejtõ Enyedi György, a tanulmányait Padovában végzõ Göcs Pál, a danzigi származású Radicius Bálint voltak a legkiválóbbak; a lektorok közül Járai Sámuel és a sokszor meghurcolt Árkosi Gelei Benedek. Mivel 1660-ban a lengyel szociniánusok közül azokat, akik ragaszkodtak vallásukhoz, kiûzték hazájukból és sokan közülük Erdélyben s éppen Kolozsváron telepedtek meg, ezért a XVII. század második felétõl kezdve aránylag sok lengyel származású lektort találunk a tantestületben.

<h3><a name="#004">Küzdelmes évek</a></h3>
<p>Az önálló erdélyi fejedelemség megszûnésének átmeneti szakasza és a XVIII. század elsõ fele a megpróbáltatások korát jelentette az iskola történetében. Ma is csodálattal és elismeréssel emlékezhetünk vissza arra a hõsi magatartásra, amellyel az iskola tanulói, tanárai és természetesen az erdélyi unitáriusok védték a mûvelõdésnek ezt a szerény, de számukra felmérhetetlen értékû intézményét.
<p>A Habsburgok uralma a híres Leopoldi diploma kiadásával kezdõdött el, amely elvileg biztosította ugyan a korábbi szabadságjogokat és kiváltságokat, és a katolikus vallást is méltán - de nem méltó módszerekkel - igyekezett visszaállítani elvesztett jogaiba. Kolozsváron 1693. október 10-én, bizonyos anyagi kárpótlás ellenében, elvették az óvári iskolát, és a tanulóifjúság a piac nyugati oldalán kapott három, iskolai célokra alig alkalmas magánházat. 1695 - 1697 között, részben e házak átalakításával, részben pedig új helyiségek építésével, az iskola végre megfelelõ épületekhez jutott.  
<p>Az építkezés még be sem fejezõdött, amikor 1697. május 6-án a városban iszonyú tûz támadt, amely az egykori feljegyzések szerint "három templommal, két scholával, toronnyal együtt, a városnak nagyobb részét elpusztította úgy, hogy harmada, ha megmaradt".
<p>Mivel ismét építkezni kellett, és pénz nem volt, az iskola rektorát, Kolozsvári Dimén Pált Hollandiába küldték építési segély gyûjtésére. Dimén nem remélt nagy összeget, több mint 17 ezer forinttal tért vissza, ami azután elegendõ volt a tûzkárok rendbehozására. Az egykori feljegyzések beszámolnak a város és az iskola nehéz helyzetérõl a Rákóczi Ferenc vezette szabadságharc idején. Sok diák a kurucokhoz szökött át, nem volt biztosítva az ellátás, a tanulóifjúságot õrségekbe szervezték, de a közmondás ellenére a fegyverek között sem hallgattak el a múzsák, és a tanítás, megcsappant létszámmal ugyan, de tovább folyt. Az egyik korabeli feljegyzés elmondja, hogy 1708. július 19-én 40 diák aratni ment a rektornak, munkájukat azonban a kurucok megzavarták, és hármat közülük elfogtak, de hosszú alkudozások után szabadon engedték. A rektor és a lektorok, úgy látszik gyakran vették igénybe a diákokat mezei munkára, mert 1725-ben a konzisztórium a következõ határozatot hozta: "A scholamesterek tanítványaikat paraszti magok munkájára, mezei robotára, marhák körül való forgolódásra, favágásra, vízhordásra nullo sub praetextu applikálni ne merészeljenek sub poena fl. 3, hogy a tanulástól el ne vonassanak."
<p>A Rákóczi-szabadságharc befejezése után új politikai helyzet alakult ki, és a császári udvar minden eszközt felhasznált a protestánsok visszaszorítására. Steinville tábornok katonái 1716-ban elvették a nagypiaci (a mostani fõtér) templomot, ekkor a benne elhelyezett könyvnyomda és iskolai könyvtár is elpusztult. Két év múlva a piaci iskolát javaival együtt minden kárpótlás nélkül elvették, és 1718. április 2-án, a rektor és két lektor vigasztaló és buzdító szavai után a reményét vesztett ifjúság közül ki-ki a városban szerzett lakására vonult vissza. A kilátástalan helyzet ellenére a vezetõség aránylag rövid idõ alatt megtalálta a szükséges megoldást. Már május elsején az iskola kiváló lektora, Szent Ábrahámi Mihály értesítette a dispersa iuventust - a szétszéledt ifjúságot -, hogy a tanítás a Bel-Magyar utcában átengedett ház négy földszinti és két emeleti termében megkezdõdik. Szent-Ábrahámi Mihály iskolai pályáját két új tantárgy, a jog és a földrajz bevezetésével kezdte meg. Dimén halála után, 1720-ban, mint külföldön (Hollandiában és Németországban) tanult ifjú, õ vette át az iskola vezetését. Mivel az anyagi alapokat elvették, õ látta el a collaboratorok segítségével a lektorok feladatait is. Átszervezte az iskola egész rendjét, új szabályok bevezetésével helyreállította a meglazult fegyelmet, õ tiltotta el például a dohányzást, a herba nicotinianá-nak a használatát, és bizonyos mértékben korlátozta a diákgyûlés - coetus - hatáskörét. Hogy a tanulók alapos felkészülését biztosítsa, több tárgyból, - számtanból, logikából, földrajzból, világ- és egyháztörténetbõl, hittanból - tankönyvet írt.

<h3><a name="#005">Az iskola belsõ rendje</a></h3>
<p>Az iskola belsõ életérõl értékes adatokat tartalmaznak azok a rendszeresen vezetett feljegyzések, amelyek az anyagi számadások mellett a fontosabbnak tartott eseményekrõl is beszámolnak. 1626-tól kezdõdõen - kisebb-nagyobb megszakításokkal a múlt század közepéig - külön naplóba az ún. Fasciulus Rerum Scholasticariumba vezették. Kiderül belõle a tanulók küzdelme, meg nem szûnõ tevékenysége az anyagiak biztosítására. Ez a tevékenység nagyon változatos volt: énekeltek a temetéseken, üdvözlõ szavakat, verseket mondtak és énekeltek a lakodalmakon és a vendégségeken, karácsonykor csoportokba szervezõdve "kántáltak" a gazdagabb polgárok házainál, elmentek legációra, virrasztottak a betegek ágyainál, "asszisztáltak" az ünnepi szertartásokon, magántanítást vállaltak, és nem vonakodtak a mezei munkától: kapálástól, aratástól. kaszálástól, szénagyûjtéstõl. A begyûlt összegeket idõrõl idõre szétosztották, elsõsorban a rászoruló tanulók között.
<p>Életüket az iskolában és a bentlakásban maguk irányították. A diákgyûlés gondoskodott a fegyelem magatartásáról, a kihágások, vétségek számbavételérõl és szigorú megbüntetésérõl. A büntetést, akárcsak más iskolákban is - mai fogalmaink szerint - a túlzott szigorúság jellemezte. Ide tartozott a koplaltatás, kikötés, bebörtönzés és a kicsapás; az alsóbb csoportoknál a vesszõzés. Sajátos büntetési forma volt a plága, melynek célja a latin nyelv alapos elsajátítása. Minden csoport egyik tagjának a lektor nádpálcát  - plágát - adott át, aki annak adta tovább, akit anyanyelvén hallott beszélni. Ha a plága több mint két napig maradt nála, akkor régebben egy nummus (pénz) bírságot fizetett, késõbb 12 sor latin verset, vagy ennek megfelelõ prózát kellett megtanulnia, vagy 12 mondatot a bibliából. Alkalmazásának utolsó szakaszában ismét a pénzbírságra tértek át. A verés sem volt ritka fegyelmezési módszer; hogy "a gyermekeket kézzel vagy bottal ne verjék ... csak pálcával, 3 frt. büntetés mellett".
<p>A felsõosztályosok felszabadultak a pálca uralma alól, és mint tógások vagy secundanusok külön szervezetbe - coetusba - tömörültek. Az önkormányzati rendszer érvényesítésére a diákság valóságos "tisztviselõi kart" választott, melynek minden tagja feladatának tartotta a hagyomány megõrzését és alkalmazását. Külön szervezet volt az "esküdtszék", amely kivizsgált és megbüntetett minden fegyelmi kihágást. A múlt század második felében Benczédi Gergely felújította ezt az intézményt, és 1947-ben új alapokra helyezve mi is alkalmaztuk, és örömmel állapíthattuk meg, hogy mûködése eredményesebb és hathatósabb volt, mint az igazgató vagy a tantestület fegyelmezése. 
<p>A diákság életébõl természetesen nem hiányzott a szórakozás sem, és a hét bizonyos délutánjait szabadtéri játékokkal töltötte, ahogy ma mondanánk: "a sportnak szentelte", és sok gondot fordított a színjátszásra. A színjátszás irányítása a rektor és a senior hatáskörébe tartozott. 1572 áprilisában elõadták Válaszúti György, az iskola seniorának darabját, A debreceni disputát, talán ez az elsõ magyar nyelvû iskolai színjáték, amelynek elõadásáról adatunk van. 1626. március 21-én Bethlen Gábor fejedelem és kísérete is részt vett az iskola egyik színielõadásán. Ma már több darab címét vagy éppen kéziratát ismerjük, s feltehetõ, hogy még nem egy lappang különbözõ könyvtárainkban.

<h3><a name="#006">Az iskola a XVIII. században és a reformkorban</a></h3>
<p>A sebtében átalakított magánház csakhamar nem volt elegendõ a tanulók befogadására. Ezért õk maguk építettek agyaggal döngölt sövényfalakból új helyiségeket: 1726-ban ugyancsak négyet. Az alapítványi vagyon elvétele után az egyetemes egyház gyûjtésekbõl tartotta fenn az iskolát, annál is inkább, mert 1724-tõl kezdve az iskola fenntartása az egyházközségtõl az egyetemes egyház hatáskörébe ment át. A gyûjtések nem jártak mindig kellõ eredménnyel, s ilyenkor a tantestület fizetése és a tanulók segélyezése elmaradt. Közben a felekezet tagjai elõtt bezárulnak a közhivatalok is, és a fõurak néhány kivételével, más vallásra tértek. A megmaradottak különösen a Sukiak és a Petrichevich-Horváthok a szó szoros értelmében "táplálták a tanárokat és a tanulókat". A gyûjtések és adományozások folytán mégis akkora összeg gyûlt össze, hogy 1780-ra az iskolát egy emeletig felépítették, 1806-ban pedig befejezhették a második emelet építését is. Így épült fel a "régi kollégium", amely összesen 30 helyiséget foglalt magában. A termek számmal és külön névvel voltak jelölve, például "Róma", "Dézsmacsûr" stb. Ilyen módon az iskola épületének kérdése csaknem egy évszázadra megoldódott.
<p>A XVIII. század folyamán a felvilágosodás szelleme, ha lassan is, éreztette hatását. Mária Terézia 1777-ben kiadta a tanítás egységes rendszerét és szellemét megkívánó rendeletet, a Ratio educationist. Magas követelményeinek azonban az erdélyi iskolák nem tudtak eleget tenni, ezért II. József 1782-ben Erdélyben bevezeti az ún. Norma regiát, amely csökkentette a Ratio túlzsúfolt tantervét, és a hangsúlyt az irodalmi és az esztétikai nevelésre helyezte. Az erdélyi iskolák ennek alkalmazásától is idegenkedtek, mert belügyeikbe való beleszólásnak tekintették. Néhány hónappal késõbb megjelent a Türelmi rendelet, amely a felvilágosodás szellemében bizonyos enyhítéseket hozott, sõt az iskolának 63 évvel korábban elvett javaiért II. József  5000 forint kárpótlást adott. Az így megindult folyamat kedvezõ légkört teremtett, mert elkerülhetetlenül a vallásszabadság és az alkotmányosság helyreállítása felé haladt, ami lehetõvé tette az iskolában is a reformok egymás utáni alkalmazását. 
<p>A tárgyalt korszak igazgatói és tanárai közül messze kimagaslik Szent Ábrahámi Mihály, Ágh István, a jobbágyszármazású szülõktõl származó Lázár István, a késõbbi püspök, a költõ és történész Székely Sándor, a "Vadrózsák" gyûjtõje, Kriza János, a jogtudós Mikó Lõrinc és mindenek elõtt Brassai Sámuel, aki két ízben is betöltötte az igazgatói tisztet (1838-1840 és 1845-1847 között). 
<p>Nincs helyünk kitérni itt mindazokra a tantervi és módszertani változásokra, amelyek a nevelést és az oktatást összhangba hozták az idõk követelményeivel. Néhányat azonban mégsem mellõzhetünk: megváltoztak a tantestület címei: a rektorból igazgató, azaz tanár lett; új tantárgyak kerültek be a tantervbe; elmaradtak a régi középkorias szokások, a diákgyûlés hatáskörét mindinkább az igazgató vette át; korszerûsödött a tanterv, és a szabadelvû eszmék úgy otthonra találtak a múzsáknak ebben a hajlékában, mint a XVI. században a racionalizmus dogmaellenessége.
<p>Az iskola didaktikai, pedagógiai, szellemi fejlõdését nagymértékben elõmozdította Brassai Sámuel. 1837-ben már mint ismert tudós lett az iskola tanára, s azt a feladatot kapta, hogy új, a követelményeknek jobban megfelelõ tantervet dolgozzon ki. Tantervében Brassai csaknem teljes mértékben szakított az évszázados hagyományos felfogással, és a latin nyelv uralmát megdöntve az anyanyelvi oktatást vezette be. A csoportrendszert a szakrendszerrel helyettesítette, vagyis a tanár nem egy egész csoportot tanított mindenbõl, hanem egy vagy két tárgyat minden vagy legalábbis a legtöbb csoportban. Nyilván, ez a tantestület szûkebb szakosítását, de alaposabb felkészülését kívánta meg. A csoportokat osztályokkal cserélte fel, és ezek számozását alulról felfelé jelölte. Az oktatás elmélyítésére megkövetelte a tankönyvek rendszeres használatát, és õ maga hét tankönyvet írt. Az esztétikai és irodalmi oktatás mellett a korábban elhanyagolt reáltudományok: a matematika, fizika, természettan, ásványtan, növénytan alaposabb mûvelését is megkívánta, és nagy súlyt helyezett a szertárak rendszeres gyarapítására.
<p>Brassai tervének gyakorlatba ültetésével az iskola nagy lépést tett elõre, és sok tekintetben az erdélyi nevelés élvonalába került.
<p>A reformkor más újításokat is hozott: különvált a teológiai tanfolyam, elõbb két-, majd három-, végül négyéves idõtartammal önálló akadémiává fejlõdött. 1847-ben jogtudományi tanszéket is létesítettek, de az alapítvány megsemmisülése miatt ez csak egy évig mûködhetett.

<h3><a name="#007">1848 és az azt követõ idõszak</a></h3>
<p>Az 1848-as szabadságharc idején az iskola épületét katonai kórháznak foglalták le, és a tanulók nagy része bevonult katonának, ezért a tanítás egy ideig szünetelt. A forradalmi harc bukása után az erdélyi helytartóság elismerte az iskola mûködési jogát, sõt fõgimnáziumnak nyilvánította, a jogi tanfolyamot megszüntette, és a filozófiát beolvasztotta a fõgimnáziumi 
<p>tantervbe. Az új nevelésügyi rendelet, az Entwurf  biztosította az állam ellenõrzési jogát az iskolák fölött. Ekkor jött létre a fõgimnázium, amely négy alsó osztályú gimnáziumból és a filozófiát kurzust egységesítõ négy felsõ osztályból állott.
<p>Az Entwurf az erdélyi iskolákban határozott ellenkezést váltott ki. 1860-ban ebbe az iskolába látszólag annak a szellemében, de a valóságban a Brassai-tantervnek megfelelõ rendszert vezettek be. Ezzel indul meg az a folyamat, amely az iskolát mindinkább modernizálja és színvonalassá teszi. A folyamatot elõmozdító számos ok közül csak néhányat említünk meg:
<p>A szabadelvûség fokozatos fejlõdése lassanként feloldotta az unitáriusok iránt különösen a magasabb körökben táplált elõítéletet. Ennek szétoszlatásához nem kis mértékben járult hozzá az a tény, hogy "felfedezõdtek" az angol hitrokonok, akik már az abszolutizmus éveiben hathatós segítséget nyújtottak. A megváltozott hangulat eredménye az iskola számára az lett, hogy más felekezetû és nemzetiségû tanulók: románok, németek, fõképpen zsidók egyre nagyobb számban látogatták. Ennek szemléltetésére csak egy példát hozunk fel: 1913-14-ben a tanulók száma a nyolc osztályban 344, ebbõl 128, vagyis több mint egyharmad más vallású.
<p>Fejlõdését elõsegítette a kolozsvári egyetem létesítése 1872-ben, amely biztosítani tudta a tantestület megfelelõ utánpótlását. Az iskola korábban is arra törekedett, hogy az alapítólevélnek megfelelõen "tudós és nyelvekben jártas tanárokat" alkalmazzon. A rektor és legtöbbször a tanárok is külföldön: olasz, holland és német egyetemeken tanultak, majd 1860-tól az angol fõiskolákon létesítettek ösztöndíjakat számukra. A kolozsvári egyetem alapítása nyomán a külföldi tanulmányok nem maradtak el, de a megnövekedett tantestület valamennyi tagja alapos képzésben részesülhetett. 
<p>E korszak igazgatói és tanárai közül csak a legkiválóbbakat említhetjük meg: a gazdag publicisztikai tevékenységet is kifejtõ Nagy Lajost, a már Angliában tanulmányokat folytató Benczédi Gergelyt és Kovács Jánost, az iskola történetének alapos kutatóját és ismerõjét, Gál Kelement, a tanárok közül Simén Domokost, Kanyaró Ferencet, Uzoni Fosztó Gábort, Pálfi Mártont, Nyiredy Gézát, Kelemen Lajost, Varga Bélát, Gelei Józsefet, Borbély Istvánt, akik mind didaktikai, mind pedig irodalmi vagy tudományos munkásságukkal általános elismerést váltottak ki. 
<p>Nem kis mértékben járultak hozzá az iskola fellendüléséhez a nagylelkû adakozók. Közöttük elsõ helyen Berde Mózes áll, aki 1888 szeptemberében kelt végrendeletében csaknem egymillió értékû vagyont hagyott egyházának, s ebbõl százezer forintot a kolozsvári iskola számára, mert amint írta: "Kora ifjúságomból szívem egy érzést, agyam egy gondolatot táplált: felsegíteni szegény vallás közösségemet, könnyíteni az utat a tanuló fiatalságnak a tudományok megszerzésére és segélyezni elhagyott szolgáit és tanárait". Az adományozások tették lehetõvé a könyvtárak, szertárak gyarapítását. Már a XVIII. században a külföldre küldött ifjak kötelezték magukat, hogy könyveket vásárolnak, és idõvel azokat az iskolának adományozzák. Bölöni Farkas Sándor, Brassai Sámuel és sokan mások könyvtárukat adományozták az iskolának.
<p>Lassanként olyan anyagi alapok gyûltek össze, amelyek 1897-ben lehetõvé tették a mostani iskola felépítésének megkezdését, amely Pákei Lajos tervei szerint négy év alatt készült el. Az épületet 1901. szeptember 21-én ünnepélyes megnyitó keretében adták át rendeltetésének Erdély egyik legnagyobb s legszebb iskolaépületeként. Büszke volt rá minden tanulója, tanára s 
talán Kolozsvár valamennyi lakója. Nicolae Iorga, a nagy román történész, amikor a húszas években felkereste Kolozsvárt, azt írta róla, hogy egyetemnek beillõ, valóságos palota.
<p>A késõbbi fejlõdés már mindannyiunk elõtt ismert. Erdélynek Romániával való egyesülése után mint felekezeti iskola államsegélyben ugyan nem részesült, de szabadon mûködhetett, és mint néhány évszázadon át, a hívek adakozása lehetõvé tette az anyagi alapok biztosítását. A második világháború zivatarában ágyúgolyó-találat érte, de a fõhatóság és az iskola vezetõsége rövid idõ alatt nemcsak a keletkezett rongálódásokat javíttatta ki, hanem az épület általános rendbetételére számottevõ anyagi áldozatot hozott. A második világháború után az állam megkülönböztetés nélkül biztosította a felekezeti iskolák tantestületének fizetését, a tanári kar igazódott az új követelményekhez, és a háború okozta nehézségek ellenére a tanítás zavartalanul, megnövekedett létszámmal folyt.
	
<h3><a name="#008">Az iskola az államosítás után</a></h3>
<p>Az 1948 augusztusában életbe lépett tanügyi reform teljesen új alapokra helyezte a hazai oktatást. Az iskola minden fokon az állam fenntartása, irányítása és ellenõrzése alá került. A reform az egész ifjúság nemre, vallásra és nemzetiségre való tekintet nélkül, egységes nevelését és oktatását tûzte ki célul.
<p>Hosszú történetének ezt a szakaszát dr. Gaál Györgynek, az iskola 1991 - 1992. évi évkönyvében (5.-7.) közölt tanulmánya alapján ismertetjük.
<p>Az 1948. augusztusában államosított iskola az "1-es számú Magyar Fiúlíceum" nevet kapta és az egységes állami tantervek alapján, kitûnõ tanári karral kezdett mûködni. Kétségtelen a város egyik legnagyobb és legjobb iskolája maradt, 1949-ben bevezették az esti tagozatot; az 1954-ben elrendelt új számozás folytán "7-es számú Líceum" lett. Fennállásának 400. évfordulója alkalmából 1957-ben, az illetékes felsõbb hatóságok engedélyével a "Brassai Sámuel Líceum" nevet vette fel. A magyarországi forradalmat követõ politikai tisztogatások és koncepciós perek következtében 1957-ben több kiváló tanárát elbocsátották.
<p>1962-ben négy román osztály beindításával megalakul az esti líceumi román tagozat, amelynek élére aligazgatót állítottak; 1962-tõl pedig német tagozattal bõvült. 1963-ban megtiltják a Brassai Sámuel név használatát, de hét év múlva, 1970-ben, államtanácsi határozattal ismét engedélyezik. 
<p>Az 1960-as évek végén és a következõ évtized elején határozott fellendülés tapasztalható az iskola életében: megjelenik a "Fiatal szívvel" címû diákfolyóirat, megszervezik a "Brassai Hetet" és a sportélet fellendítésére "Brassai Kupát" létesítenek (1980), különbözõ alapítványokat hoznak létre.
<p>1977-ben a Brassait, sok más iskolához hasonlóan, ipari líceumnak alakították át, ami sok tehetséges diák távozását vonta maga után. 1972-ben a német tagozatot a Cosbuc Líceumba helyezték át; 1985 õszétõl kezdve pedig a nappali tagozaton is román tannyelvû osztályokat 
indítottak be. Mivel ezzel párhuzamosan a magyar osztályok számát csökkentették, a román osztályok tanulóinak jó része magyar anyanyelvû volt. Ugyanakkor a magyar feliratokat és a régi érettségi tablókat leszedették.
<p>Az 1989. decemberi változás után, - amint ez az 1990. január 19-iki felterjesztésbõl kitûnik - a közel 2500 tanulót számláló "iskolakombinát"-ból a nappali tagozat román tannyelvû osztályait az újonnan létesített "Avram Iancu" Líceumba költöztették át, kivéve azokat a diákokat, akik a magyar tagozatra iratkoztak át. Az esti román tagozat is az iskolában maradt ugyan, de mostantól kezdve az iskola ismét visszakapta magyar jellegét.
<p>A tanulók önképzését számos tudományos-, mûvészeti és sportkör biztosítja, amelyek a "Kriza János" Önképzõ Kör tagozatai. Iskolai lap jelenik meg évente négyszer. A "Brassai Kupa" elnyeréséért évenkénti sportversenyeket szerveznek.  

<b><i>(Bodor András: Iskolánk történetébõl)</i></b>
<p>

<h3><a href="#009">A Brassai Sámuel Líceum 1985 után:</a></h3>
<p>1985-ben létesül a Bogáncs néptáncegyüttes, táncházmozgalom indul a Brassaiban az akkor oda került Tolna Éva tanárnõ vezetésével
<p>1990-ben Zwolle-ból a Carolus Clusius iskola vezetõsége keresi fel az iskolát, egyúttal segélyszállítmányt hoznak. A látogatás eredményeképpen a két intézmény testvériskolai kapcsolatba kerül.  
<p>1990-ben bejegyzik hivatalos jogi személynek a Brassais Véndiák Alapítványt, melynek Szabó Zsolt lesz az elnöke
<p>1990-ben egy soproni iskolával is testvériskolai kapcsolat alakul ki
<p>1993-ban a Brassais Véndiák Alapítvány Hantz Irén tanárnõ javaslatára Torockón házat vesz. A házvételben Dr. Tobias Károly, valamint az iskola német, magyar, és holland barátai segítenek.  
<p>1993. szeptember 24-én avatják a Torockói Házat

<h4><a href="#000">Vissza</a></h4>
	</td>
</tr>
</table>
<?PHP  include ("homefooter.php");?>